/**
 * Monaco, as this app uses it: the editor with its standard features and syntax highlighting
 * for every language Monaco knows, but none of the language services (TypeScript, JSON, CSS,
 * HTML) or the LSP client that `editor.main` also pulls in. The app is not an IDE (vision,
 * non-goals); the learner's own editor is. Everything is bundled: no CDN (D9).
 *
 * The list mirrors monaco-editor 0.57 `esm/vs/editor/editor.main.js`; regenerate it when Monaco
 * is updated. Loaded only in the real app (lazily): tests replace the editor with a textarea.
 */
import EditorWorker from 'monaco-vs/editor/editor.worker.js?worker';
import * as monaco from 'monaco-vs/editor/editor.api.js';

import 'monaco-vs/editor/contrib/anchorSelect/browser/anchorSelect.js';
import 'monaco-vs/editor/contrib/bracketMatching/browser/bracketMatching.js';
import 'monaco-vs/editor/contrib/caretOperations/browser/transpose.js';
import 'monaco-vs/editor/contrib/clipboard/browser/clipboard.js';
import 'monaco-vs/editor/contrib/codeAction/browser/codeActionContributions.js';
import 'monaco-vs/editor/browser/widget/codeEditor/codeEditorWidget.js';
import 'monaco-vs/editor/contrib/codelens/browser/codelensController.js';
import 'monaco-vs/base/browser/ui/codicons/codicon/codicon.css';
import 'monaco-vs/editor/contrib/colorPicker/browser/colorPickerContribution.js';
import 'monaco-vs/editor/contrib/comment/browser/comment.js';
import 'monaco-vs/editor/contrib/contextmenu/browser/contextmenu.js';
import 'monaco-vs/editor/contrib/cursorUndo/browser/cursorUndo.js';
import 'monaco-vs/editor/browser/widget/diffEditor/diffEditor.contribution.js';
import 'monaco-vs/editor/contrib/diffEditorBreadcrumbs/browser/contribution.js';
import 'monaco-vs/editor/contrib/dnd/browser/dnd.js';
import 'monaco-vs/editor/contrib/documentSymbols/browser/documentSymbols.js';
import 'monaco-vs/editor/contrib/dropOrPasteInto/browser/dropIntoEditorContribution.js';
import 'monaco-vs/features/find/register.js';
import 'monaco-vs/editor/contrib/floatingMenu/browser/floatingMenu.contribution.js';
import 'monaco-vs/editor/contrib/folding/browser/folding.js';
import 'monaco-vs/editor/contrib/fontZoom/browser/fontZoom.js';
import 'monaco-vs/editor/contrib/format/browser/formatActions.js';
import 'monaco-vs/editor/contrib/gotoError/browser/gotoError.js';
import 'monaco-vs/editor/standalone/browser/quickAccess/standaloneGotoLineQuickAccess.js';
import 'monaco-vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.js';
import 'monaco-vs/editor/contrib/gpu/browser/gpuActions.js';
import 'monaco-vs/editor/contrib/hover/browser/hoverContribution.js';
import 'monaco-vs/editor/contrib/indentation/browser/indentation.js';
import 'monaco-vs/editor/contrib/inlayHints/browser/inlayHintsContribution.js';
import 'monaco-vs/editor/contrib/inlineCompletions/browser/inlineCompletions.contribution.js';
import 'monaco-vs/editor/contrib/inlineProgress/browser/inlineProgress.js';
import 'monaco-vs/editor/contrib/inPlaceReplace/browser/inPlaceReplace.js';
import 'monaco-vs/editor/contrib/insertFinalNewLine/browser/insertFinalNewLine.js';
import 'monaco-vs/editor/standalone/browser/inspectTokens/inspectTokens.js';
import 'monaco-vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard.js';
import 'monaco-vs/editor/contrib/lineSelection/browser/lineSelection.js';
import 'monaco-vs/editor/contrib/linesOperations/browser/linesOperations.js';
import 'monaco-vs/editor/contrib/linkedEditing/browser/linkedEditing.js';
import 'monaco-vs/editor/contrib/links/browser/links.js';
import 'monaco-vs/editor/contrib/longLinesHelper/browser/longLinesHelper.js';
import 'monaco-vs/editor/contrib/middleScroll/browser/middleScroll.contribution.js';
import 'monaco-vs/editor/contrib/multicursor/browser/multicursor.js';
import 'monaco-vs/editor/contrib/parameterHints/browser/parameterHints.js';
import 'monaco-vs/editor/contrib/placeholderText/browser/placeholderText.contribution.js';
import 'monaco-vs/editor/standalone/browser/quickAccess/standaloneCommandsQuickAccess.js';
import 'monaco-vs/editor/standalone/browser/quickAccess/standaloneHelpQuickAccess.js';
import 'monaco-vs/editor/standalone/browser/quickAccess/standaloneGotoSymbolQuickAccess.js';
import 'monaco-vs/editor/contrib/readOnlyMessage/browser/contribution.js';
import 'monaco-vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch.js';
import 'monaco-vs/editor/contrib/rename/browser/rename.js';
import 'monaco-vs/editor/contrib/sectionHeaders/browser/sectionHeaders.js';
import 'monaco-vs/editor/contrib/semanticTokens/browser/viewportSemanticTokens.js';
import 'monaco-vs/editor/contrib/smartSelect/browser/smartSelect.js';
import 'monaco-vs/editor/contrib/snippet/browser/snippetController2.js';
import 'monaco-vs/editor/contrib/stickyScroll/browser/stickyScrollContribution.js';
import 'monaco-vs/editor/contrib/suggest/browser/suggestInlineCompletions.js';
import 'monaco-vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast.js';
import 'monaco-vs/editor/contrib/toggleTabFocusMode/browser/toggleTabFocusMode.js';
import 'monaco-vs/editor/contrib/tokenization/browser/tokenization.js';
import 'monaco-vs/editor/contrib/unicodeHighlighter/browser/unicodeHighlighter.js';
import 'monaco-vs/editor/contrib/unusualLineTerminators/browser/unusualLineTerminators.js';
import 'monaco-vs/editor/contrib/wordHighlighter/browser/wordHighlighter.js';
import 'monaco-vs/editor/contrib/wordOperations/browser/wordOperations.js';
import 'monaco-vs/editor/contrib/wordPartOperations/browser/wordPartOperations.js';
import 'monaco-vs/editor/browser/coreCommands.js';
import 'monaco-vs/editor/contrib/caretOperations/browser/caretOperations.js';
import 'monaco-vs/editor/contrib/dropOrPasteInto/browser/copyPasteContribution.js';
import 'monaco-vs/editor/contrib/find/browser/findController.js';
import 'monaco-vs/editor/contrib/gotoSymbol/browser/goToCommands.js';
import 'monaco-vs/editor/contrib/gotoError/browser/markerSelectionStatus.js';
import 'monaco-vs/editor/contrib/semanticTokens/browser/documentSemanticTokens.js';
import 'monaco-vs/editor/contrib/suggest/browser/suggestController.js';
import 'monaco-vs/editor/common/standaloneStrings.js';
import 'monaco-vs/base/browser/ui/codicons/codicon/codicon-modifiers.css';

import 'monaco-vs/languages/definitions/abap/register.js';
import 'monaco-vs/languages/definitions/apex/register.js';
import 'monaco-vs/languages/definitions/azcli/register.js';
import 'monaco-vs/languages/definitions/bat/register.js';
import 'monaco-vs/languages/definitions/bicep/register.js';
import 'monaco-vs/languages/definitions/cameligo/register.js';
import 'monaco-vs/languages/definitions/clojure/register.js';
import 'monaco-vs/languages/definitions/coffee/register.js';
import 'monaco-vs/languages/definitions/cpp/register.js';
import 'monaco-vs/languages/definitions/csharp/register.js';
import 'monaco-vs/languages/definitions/csp/register.js';
import 'monaco-vs/languages/definitions/css/register.js';
import 'monaco-vs/languages/definitions/cypher/register.js';
import 'monaco-vs/languages/definitions/dart/register.js';
import 'monaco-vs/languages/definitions/dockerfile/register.js';
import 'monaco-vs/languages/definitions/ecl/register.js';
import 'monaco-vs/languages/definitions/elixir/register.js';
import 'monaco-vs/languages/definitions/flow9/register.js';
import 'monaco-vs/languages/definitions/fsharp/register.js';
import 'monaco-vs/languages/definitions/freemarker2/register.js';
import 'monaco-vs/languages/definitions/go/register.js';
import 'monaco-vs/languages/definitions/graphql/register.js';
import 'monaco-vs/languages/definitions/handlebars/register.js';
import 'monaco-vs/languages/definitions/hcl/register.js';
import 'monaco-vs/languages/definitions/html/register.js';
import 'monaco-vs/languages/definitions/ini/register.js';
import 'monaco-vs/languages/definitions/java/register.js';
import 'monaco-vs/languages/definitions/javascript/register.js';
import 'monaco-vs/languages/definitions/julia/register.js';
import 'monaco-vs/languages/definitions/kotlin/register.js';
import 'monaco-vs/languages/definitions/less/register.js';
import 'monaco-vs/languages/definitions/lexon/register.js';
import 'monaco-vs/languages/definitions/lua/register.js';
import 'monaco-vs/languages/definitions/liquid/register.js';
import 'monaco-vs/languages/definitions/m3/register.js';
import 'monaco-vs/languages/definitions/markdown/register.js';
import 'monaco-vs/languages/definitions/mdx/register.js';
import 'monaco-vs/languages/definitions/mips/register.js';
import 'monaco-vs/languages/definitions/msdax/register.js';
import 'monaco-vs/languages/definitions/mysql/register.js';
import 'monaco-vs/languages/definitions/objective-c/register.js';
import 'monaco-vs/languages/definitions/pascal/register.js';
import 'monaco-vs/languages/definitions/pascaligo/register.js';
import 'monaco-vs/languages/definitions/perl/register.js';
import 'monaco-vs/languages/definitions/pgsql/register.js';
import 'monaco-vs/languages/definitions/php/register.js';
import 'monaco-vs/languages/definitions/pla/register.js';
import 'monaco-vs/languages/definitions/postiats/register.js';
import 'monaco-vs/languages/definitions/powerquery/register.js';
import 'monaco-vs/languages/definitions/powershell/register.js';
import 'monaco-vs/languages/definitions/protobuf/register.js';
import 'monaco-vs/languages/definitions/pug/register.js';
import 'monaco-vs/languages/definitions/python/register.js';
import 'monaco-vs/languages/definitions/qsharp/register.js';
import 'monaco-vs/languages/definitions/r/register.js';
import 'monaco-vs/languages/definitions/razor/register.js';
import 'monaco-vs/languages/definitions/redis/register.js';
import 'monaco-vs/languages/definitions/redshift/register.js';
import 'monaco-vs/languages/definitions/restructuredtext/register.js';
import 'monaco-vs/languages/definitions/ruby/register.js';
import 'monaco-vs/languages/definitions/rust/register.js';
import 'monaco-vs/languages/definitions/sb/register.js';
import 'monaco-vs/languages/definitions/scala/register.js';
import 'monaco-vs/languages/definitions/scheme/register.js';
import 'monaco-vs/languages/definitions/scss/register.js';
import 'monaco-vs/languages/definitions/shell/register.js';
import 'monaco-vs/languages/definitions/solidity/register.js';
import 'monaco-vs/languages/definitions/sophia/register.js';
import 'monaco-vs/languages/definitions/sparql/register.js';
import 'monaco-vs/languages/definitions/sql/register.js';
import 'monaco-vs/languages/definitions/st/register.js';
import 'monaco-vs/languages/definitions/swift/register.js';
import 'monaco-vs/languages/definitions/systemverilog/register.js';
import 'monaco-vs/languages/definitions/tcl/register.js';
import 'monaco-vs/languages/definitions/twig/register.js';
import 'monaco-vs/languages/definitions/typescript/register.js';
import 'monaco-vs/languages/definitions/typespec/register.js';
import 'monaco-vs/languages/definitions/vb/register.js';
import 'monaco-vs/languages/definitions/wgsl/register.js';
import 'monaco-vs/languages/definitions/xml/register.js';
import 'monaco-vs/languages/definitions/yaml/register.js';

// One generic worker serves every model: there are no language services to ask for another.
(globalThis as { MonacoEnvironment?: unknown }).MonacoEnvironment = { getWorker: () => new EditorWorker() };

export { monaco };
